/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/house.glb')
  useEffect(() => {
    const mat = materials && materials['Material.008']
    if (mat) {
      mat.emissive = new THREE.Color('#3fa5ff')
      mat.emissiveIntensity = 2
      mat.needsUpdate = true
    }
  }, [materials])
  return (
    <group {...props} dispose={null}>
      <group name="RootNode" position={[4.24, 10.976, -23.174]} scale={0.01}>
        <group
          name="bloome"
          position={[411.546, 1137.923, -2540.866]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={71.339}>
          <mesh
            name="Cube080_Material013_0"
            castShadow
            receiveShadow
            geometry={nodes.Cube080_Material013_0.geometry}
            material={materials['Material.013']}
          />
          <mesh
            name="Cube080_Material013_0_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube080_Material013_0_1.geometry}
            material={materials['Material.012']}
          />
        </group>
        <mesh
          name="chapeau001_Material002_0"
          castShadow
          receiveShadow
          geometry={nodes.chapeau001_Material002_0.geometry}
          material={materials['Material.003']}
          position={[-222.857, 2190.94, 881.872]}
          rotation={[-1.397, -0.217, 0.038]}
          scale={[1277.152, 1277.152, 1277.153]}
        />
        <mesh
          name="chapeau004_Material002_0"
          castShadow
          receiveShadow
          geometry={nodes.chapeau004_Material002_0.geometry}
          material={materials['Material.003']}
          position={[-1480.386, 1313.583, 164.082]}
          rotation={[-2.249, 0.448, 0.401]}
          scale={611.384}
        />
        <mesh
          name="chapeau005_Material002_0"
          castShadow
          receiveShadow
          geometry={nodes.chapeau005_Material002_0.geometry}
          material={materials['Material.003']}
          position={[-1160.2, 1660.338, -1091.856]}
          rotation={[-1.637, -0.235, 2.888]}
          scale={1191.418}
        />
        <mesh
          name="chapeau_Material002_0"
          castShadow
          receiveShadow
          geometry={nodes.chapeau_Material002_0.geometry}
          material={materials['Material.003']}
          position={[1133.599, 2186.064, -1032.332]}
          rotation={[-1.588, -0.098, 0.015]}
          scale={1277.152}
        />
        <mesh
          name="chemine_Material007_0"
          castShadow
          receiveShadow
          geometry={nodes.chemine_Material007_0.geometry}
          material={materials['Material.007']}
          position={[562.521, 2766.474, 1072.726]}
          rotation={[-1.499, 0.378, -1.037]}
          scale={50.757}
        />
        <mesh
          name="Cube005_Material008_0"
          castShadow
          receiveShadow
          geometry={nodes.Cube005_Material008_0.geometry}
          material={materials['Material.012']}
          position={[1670.808, 3884.431, 570.698]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={114.817}
        />
        <mesh
          name="Cube006_Material008_0"
          castShadow
          receiveShadow
          geometry={nodes.Cube006_Material008_0.geometry}
          material={materials['Material.012']}
          position={[1562.087, 3916.703, 585.573]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={59.725}
        />
        <mesh
          name="Cube010_Material008_0"
          castShadow
          receiveShadow
          geometry={nodes.Cube010_Material008_0.geometry}
          material={materials['Material.012']}
          position={[1670.064, 4033.49, 549.461]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={39.418}
        />
        <mesh
          name="Cube035_Material002_0"
          castShadow
          receiveShadow
          geometry={nodes.Cube035_Material002_0.geometry}
          material={materials['Material.003']}
          position={[-1475.3, 1591.502, 269.662]}
          rotation={[1.613, -0.113, -1.359]}
          scale={61.118}
        />
        <mesh
          name="Cube036_Material002_0"
          castShadow
          receiveShadow
          geometry={nodes.Cube036_Material002_0.geometry}
          material={materials['Material.003']}
          position={[-1269.36, 1397.132, 69.557]}
          rotation={[0.338, -0.8, -2.053]}
          scale={61.118}
        />
        <mesh
          name="Cube037_Material002_0"
          castShadow
          receiveShadow
          geometry={nodes.Cube037_Material002_0.geometry}
          material={materials['Material.003']}
          position={[-1217.443, 1413.81, 181.644]}
          rotation={[1.577, -1.147, -1.662]}
          scale={41.743}
        />
        <mesh
          name="Cube038_Material002_0"
          castShadow
          receiveShadow
          geometry={nodes.Cube038_Material002_0.geometry}
          material={materials['Material.003']}
          position={[-1414.055, 1264.887, -10.364]}
          rotation={[-0.085, -0.189, -1.659]}
          scale={61.118}
        />
        <mesh
          name="Cube039_Material002_0"
          castShadow
          receiveShadow
          geometry={nodes.Cube039_Material002_0.geometry}
          material={materials['Material.003']}
          position={[-1481.737, 1484.936, 503.244]}
          rotation={[2.82, -0.124, -0.917]}
          scale={41.743}
        />
        <mesh
          name="Cube040_Material002_0"
          castShadow
          receiveShadow
          geometry={nodes.Cube040_Material002_0.geometry}
          material={materials['Material.003']}
          position={[-1517.119, 1591.501, 417.042]}
          rotation={[2.133, -0.239, -0.953]}
          scale={41.743}
        />
        <mesh
          name="Cube041_Material002_0"
          castShadow
          receiveShadow
          geometry={nodes.Cube041_Material002_0.geometry}
          material={materials['Material.003']}
          position={[-1619.78, 1456.004, 38.99]}
          rotation={[0.483, 0.302, -2.584]}
          scale={61.118}
        />
        <mesh
          name="Cube042_Material002_0"
          castShadow
          receiveShadow
          geometry={nodes.Cube042_Material002_0.geometry}
          material={materials['Material.003']}
          position={[-1581.529, 1129.424, -0.614]}
          rotation={[-0.127, -0.17, -1.677]}
          scale={48.18}
        />
        <mesh
          name="Cube043_Material002_0"
          castShadow
          receiveShadow
          geometry={nodes.Cube043_Material002_0.geometry}
          material={materials['Material.003']}
          position={[-1596.799, 1618.517, 367.022]}
          rotation={[1.78, 0.153, -1.38]}
          scale={26.44}
        />
        <mesh
          name="Cube044_Material002_0"
          castShadow
          receiveShadow
          geometry={nodes.Cube044_Material002_0.geometry}
          material={materials['Material.003']}
          position={[-1415.756, 2147.807, -1255.386]}
          rotation={[-1.574, -0.527, -0.192]}
          scale={183.792}
        />
        <mesh
          name="Cube045_Material002_0"
          castShadow
          receiveShadow
          geometry={nodes.Cube045_Material002_0.geometry}
          material={materials['Material.003']}
          position={[-735.002, 2068.159, -1199.096]}
          rotation={[-1.665, 0.472, -0.626]}
          scale={115.762}
        />
        <mesh
          name="Cube046_Material002_0"
          castShadow
          receiveShadow
          geometry={nodes.Cube046_Material002_0.geometry}
          material={materials['Material.003']}
          position={[-910.7, 1831.296, -1641.834]}
          rotation={[-2.507, 0.18, 0.159]}
          scale={148.047}
        />
        <mesh
          name="Cube047_Material002_0"
          castShadow
          receiveShadow
          geometry={nodes.Cube047_Material002_0.geometry}
          material={materials['Material.003']}
          position={[-1116.086, 1902.866, -610.698]}
          rotation={[-0.822, -0.278, -0.27]}
          scale={115.762}
        />
        <mesh
          name="Cube048_Material002_0"
          castShadow
          receiveShadow
          geometry={nodes.Cube048_Material002_0.geometry}
          material={materials['Material.003']}
          position={[-1724.264, 1703.141, -1413.556]}
          rotation={[-2.057, -1.088, -2.231]}
          scale={115.762}
        />
        <mesh
          name="Cube049_Material002_0"
          castShadow
          receiveShadow
          geometry={nodes.Cube049_Material002_0.geometry}
          material={materials['Material.003']}
          position={[-1776.89, 1607.573, -1222.803]}
          rotation={[-1.721, -1.134, -1.993]}
          scale={86.691}
        />
        <mesh
          name="Cube050_Material002_0"
          castShadow
          receiveShadow
          geometry={nodes.Cube050_Material002_0.geometry}
          material={materials['Material.003']}
          position={[-1475.814, 2010.111, -1008.516]}
          rotation={[-1.096, -0.605, -0.062]}
          scale={113.956}
        />
        <mesh
          name="Cube051_Material002_0"
          castShadow
          receiveShadow
          geometry={nodes.Cube051_Material002_0.geometry}
          material={materials['Material.003']}
          position={[-1311.277, 1768.87, -645.943]}
          rotation={[-0.811, -0.472, -0.221]}
          scale={70.877}
        />
        <mesh
          name="Cube052_Material002_0"
          castShadow
          receiveShadow
          geometry={nodes.Cube052_Material002_0.geometry}
          material={materials['Material.003']}
          position={[-560.214, 1946.808, -767.762]}
          rotation={[-1.332, 0.372, -0.183]}
          scale={115.762}
        />
        <mesh
          name="Cube053_Material002_0"
          castShadow
          receiveShadow
          geometry={nodes.Cube053_Material002_0.geometry}
          material={materials['Material.003']}
          position={[-494.128, 1922.01, -961.667]}
          rotation={[-1.656, 0.418, -0.106]}
          scale={49.717}
        />
        <mesh
          name="Cube054_Material009_0"
          castShadow
          receiveShadow
          geometry={nodes.Cube054_Material009_0.geometry}
          material={materials['Material.009']}
          position={[1432.586, 820.395, 710.854]}
          rotation={[-Math.PI / 2, 0.13, 0]}
          scale={265.226}
        />
        <mesh
          name="Cube055_Material009_0"
          castShadow
          receiveShadow
          geometry={nodes.Cube055_Material009_0.geometry}
          material={materials['Material.009']}
          position={[984.068, 816.17, 1010.197]}
          rotation={[-1.553, -0.353, 2.136]}
          scale={153.433}
        />
        <mesh
          name="Cube056_Material009_0"
          castShadow
          receiveShadow
          geometry={nodes.Cube056_Material009_0.geometry}
          material={materials['Material.009']}
          position={[1000.043, 801.918, 464.736]}
          rotation={[-1.361, 0.08, -2.801]}
          scale={176.609}
        />
        <mesh
          name="Cube057_Material009_0"
          castShadow
          receiveShadow
          geometry={nodes.Cube057_Material009_0.geometry}
          material={materials['Material.009']}
          position={[-581.202, 820.395, -401.413]}
          rotation={[-2.006, 0.205, 0.088]}
          scale={265.226}
        />
        <mesh
          name="Cube058_Material009_0"
          castShadow
          receiveShadow
          geometry={nodes.Cube058_Material009_0.geometry}
          material={materials['Material.009']}
          position={[-156.784, 820.395, -225.792]}
          rotation={[-1.327, 0.162, -2.55]}
          scale={157.348}
        />
        <mesh
          name="Cube059_Material009_0"
          castShadow
          receiveShadow
          geometry={nodes.Cube059_Material009_0.geometry}
          material={materials['Material.009']}
          position={[-216.07, 820.395, -584.329]}
          rotation={[-1.753, 0.229, -0.874]}
          scale={100.476}
        />
        <mesh
          name="Cube_Material008_0"
          castShadow
          receiveShadow
          geometry={nodes.Cube_Material008_0.geometry}
          material={materials['Material.012']}
          position={[837.24, 3450.714, 997.788]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={52.654}
        />
        <group name="dore" position={[-45.254, 951.65, 1192.054]} scale={8.25}>
          <mesh
            name="poigne_Material005_0"
            castShadow
            receiveShadow
            geometry={nodes.poigne_Material005_0.geometry}
            material={materials['Material.006']}
          />
          <mesh
            name="poigne_Material005_0_1"
            castShadow
            receiveShadow
            geometry={nodes.poigne_Material005_0_1.geometry}
            material={materials['Material.004']}
          />
          <mesh
            name="poigne_Material005_0_2"
            castShadow
            receiveShadow
            geometry={nodes.poigne_Material005_0_2.geometry}
            material={materials['Material.005']}
          />
        </group>
        <mesh
          name="ground"
          castShadow
          receiveShadow
          geometry={nodes.ground.geometry}
          material={materials['Material.010']}
          position={[45.883, 810.545, 2.919]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2195.716, 2195.715, 2195.715]}
        />
        <mesh
          name="mushroom_2"
          castShadow
          receiveShadow
          geometry={nodes.mushroom_2.geometry}
          material={materials['Material.002']}
          position={[1133.599, 2186.064, -1032.332]}
          rotation={[-1.588, -0.098, 0.015]}
          scale={1277.152}
        />
        <mesh
          name="mushroom_3"
          castShadow
          receiveShadow
          geometry={nodes.mushroom_3.geometry}
          material={materials['Material.002']}
          position={[-222.857, 2190.94, 881.872]}
          rotation={[-1.397, -0.217, 0.038]}
          scale={[1277.152, 1277.152, 1277.153]}
        />
        <mesh
          name="mushroom_4"
          castShadow
          receiveShadow
          geometry={nodes.mushroom_4.geometry}
          material={materials['Material.002']}
          position={[-1480.386, 1313.583, 164.082]}
          rotation={[-2.249, 0.448, 0.401]}
          scale={611.384}
        />
        <mesh
          name="mushroom_seed"
          castShadow
          receiveShadow
          geometry={nodes.mushroom_seed.geometry}
          material={materials['Material.003']}
          position={[1381.258, 2371.419, -167.401]}
          rotation={[-0.922, 0.011, -0.006]}
          scale={70.45}
        />
        <mesh
          name="mushroom_seed_"
          castShadow
          receiveShadow
          geometry={nodes.mushroom_seed_.geometry}
          material={materials['Material.003']}
          position={[606.556, 2593.789, 823.889]}
          rotation={[1.522, -0.782, -2.363]}
          scale={92.075}
        />
        <mesh
          name="mushroom1"
          castShadow
          receiveShadow
          geometry={nodes.mushroom1.geometry}
          material={materials['Material.002']}
          position={[-1160.2, 1660.338, -1091.856]}
          rotation={[-1.637, -0.235, 2.888]}
          scale={1191.418}
        />
        <mesh
          name="plant_2"
          castShadow
          receiveShadow
          geometry={nodes.plant_2.geometry}
          material={materials['Material.011']}
          position={[-506.692, 781.54, 1333.317]}
          rotation={[-Math.PI / 2, -0.007, -2.11]}
          scale={16.495}
        />
        <mesh
          name="plant_3"
          castShadow
          receiveShadow
          geometry={nodes.plant_3.geometry}
          material={materials['Material.011']}
          position={[365.058, 777.95, -72.391]}
          rotation={[-Math.PI / 2, 0, -0.18]}
          scale={30.53}
        />
        <mesh
          name="plant_4"
          castShadow
          receiveShadow
          geometry={nodes.plant_4.geometry}
          material={materials['Material.011']}
          position={[-1043.23, 778.854, -55.886]}
          rotation={[-Math.PI / 2, 0, 3.008]}
          scale={27.26}
        />
        <mesh
          name="plant_5"
          castShadow
          receiveShadow
          geometry={nodes.plant_5.geometry}
          material={materials['Material.011']}
          position={[195.418, 775.323, -1654.867]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={49.872}
        />
        <mesh
          name="plant1"
          castShadow
          receiveShadow
          geometry={nodes.plant1.geometry}
          material={materials['Material.011']}
          position={[1265.852, 780.738, 1057.885]}
          rotation={[-Math.PI / 2, 0, -0.698]}
          scale={20.44}
        />
        <mesh
          name="stem1"
          castShadow
          receiveShadow
          geometry={nodes.stem1.geometry}
          material={materials['Material.001']}
          position={[1242.693, 1078.941, -1019.361]}
          rotation={[-Math.PI / 2, -0.096, 0]}
          scale={61.754}
        />
        <mesh
          name="stem2"
          castShadow
          receiveShadow
          geometry={nodes.stem2.geometry}
          material={materials['Material.001']}
          position={[-91.195, 914.409, 818.48]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          name="stem3"
          castShadow
          receiveShadow
          geometry={nodes.stem3.geometry}
          material={materials['Material.001']}
          position={[-855.161, 825.048, -1229.883]}
          rotation={[-Math.PI / 2, 0, 2.979]}
          scale={68.293}
        />
        <mesh
          name="stem4"
          castShadow
          receiveShadow
          geometry={nodes.stem4.geometry}
          material={materials['Material.001']}
          position={[-1632.207, 777.617, 353.183]}
          rotation={[-Math.PI / 2, 0, 0.371]}
          scale={47.871}
        />
        <group
          name="windows"
          position={[230.925, 1209.857, 799.07]}
          rotation={[-1.521, 1.182, -0.345]}
          scale={100}>
          <pointLight
            intensity={3}
            distance={8}
            decay={2}
            color={'#ffdca3'}
            castShadow
          />
          <mesh
            name="vitre_Material006_0"
            castShadow
            receiveShadow
            geometry={nodes.vitre_Material006_0.geometry}
            material={materials['Material.008']}
          />
          <mesh
            name="vitre_Material006_0_1"
            castShadow
            receiveShadow
            geometry={nodes.vitre_Material006_0_1.geometry}
            material={materials['Material.004']}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/house.glb')
