/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/house.glb --output src/components/House.jsx 
Author: Citron Vert (https://sketchfab.com/citron.vert)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mushroom-house-4068472cb1d24d23bbab26e35601dfee
Title: Mushroom house
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/house.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[1133.599, 2186.065, -1032.332]} rotation={[-1.588, -0.098, 0.015]} scale={1277.152}>
          <mesh geometry={nodes.chapeau_Material001_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.chapeau_Material002_0.geometry} material={materials['Material.002']} />
        </group>
        <group position={[-222.857, 2190.941, 881.872]} rotation={[-1.397, -0.217, 0.038]} scale={1277.152}>
          <mesh geometry={nodes.chapeau001_Material001_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.chapeau001_Material002_0.geometry} material={materials['Material.002']} />
        </group>
        <group position={[-1480.386, 1313.583, 164.082]} rotation={[-2.249, 0.448, 0.401]} scale={611.384}>
          <mesh geometry={nodes.chapeau004_Material001_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.chapeau004_Material002_0.geometry} material={materials['Material.002']} />
        </group>
        <group position={[-1160.2, 1660.339, -1091.856]} rotation={[-1.637, -0.235, 2.888]} scale={[1191.418, 1191.418, 1191.417]}>
          <mesh geometry={nodes.chapeau005_Material001_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.chapeau005_Material002_0.geometry} material={materials['Material.002']} />
        </group>
        <mesh geometry={nodes.pied_Material_0.geometry} material={materials.Material} position={[1242.693, 1078.941, -1019.361]} rotation={[-Math.PI / 2, -0.096, 0]} scale={61.754} />
        <mesh geometry={nodes.pied001_Material_0.geometry} material={materials.Material} position={[-91.195, 914.41, 818.48]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.window_Material003_0.geometry} material={materials['Material.003']} position={[207.182, 1190.492, 801.047]} rotation={[-Math.PI / 2, 1.185, 0]} scale={124.093} />
        <mesh geometry={nodes.porte_cadre_Material003_0.geometry} material={materials['Material.003']} position={[-99.457, 1022.193, 1202.183]} scale={107.3} />
        <mesh geometry={nodes.window001_Material003_0.geometry} material={materials['Material.003']} position={[-337.23, 1236.914, 993.778]} rotation={[2.504, 0.821, 2.151]} scale={118.812} />
        <mesh geometry={nodes.chemine_Material007_0.geometry} material={materials['Material.007']} position={[562.521, 2766.475, 1072.725]} rotation={[-1.499, 0.378, -1.037]} scale={50.757} />
        <mesh geometry={nodes.porte001_Material004_0.geometry} material={materials['Material.004']} position={[-91.195, 908.531, 1244.211]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.poigne_Material005_0.geometry} material={materials['Material.005']} position={[-45.254, 951.65, 1192.054]} scale={8.25} />
        <mesh geometry={nodes.vitre_Material006_0.geometry} material={materials['Material.006']} position={[230.925, 1209.857, 799.069]} rotation={[-1.521, 1.182, -0.345]} scale={100} />
        <mesh geometry={nodes.vitre001_Material006_0.geometry} material={materials['Material.006']} position={[-350.518, 1247.791, 1001.729]} rotation={[-0.697, -0.808, 0.51]} scale={100} />
        <mesh geometry={nodes.Cube008_Material002_0.geometry} material={materials['Material.002']} position={[-923.727, 2716.957, 932.278]} rotation={[-1.473, -0.651, 0.056]} scale={143.335} />
        <mesh geometry={nodes.Cube009_Material002_0.geometry} material={materials['Material.002']} position={[193.054, 2836.884, 1431.187]} rotation={[-1.108, 0.202, 0.039]} scale={231.321} />
        <mesh geometry={nodes.Cube011_Material002_0.geometry} material={materials['Material.002']} position={[-562.231, 2397.903, 1837.29]} rotation={[-0.55, -0.357, 0.414]} scale={231.321} />
        <mesh geometry={nodes.Cube012_Material002_0.geometry} material={materials['Material.002']} position={[-226.228, 2687.802, -64.902]} rotation={[-2.363, -0.034, -2.576]} scale={231.321} />
        <mesh geometry={nodes.Cube013_Material002_0.geometry} material={materials['Material.002']} position={[113.468, 3014.049, 721.774]} rotation={[-1.623, 0.211, 0.113]} scale={190.719} />
        <mesh geometry={nodes.Cube014_Material002_0.geometry} material={materials['Material.002']} position={[-385.1, 2951.104, 1072.061]} rotation={[-1.37, -0.11, 0.072]} scale={134.741} />
        <mesh geometry={nodes.Cube015_Material002_0.geometry} material={materials['Material.002']} position={[-1088.515, 2161.091, 790.449]} rotation={[1.669, 1.258, 2.236]} scale={231.321} />
        <mesh geometry={nodes.Cube016_Material002_0.geometry} material={materials['Material.002']} position={[-585.824, 2606.325, 416.002]} rotation={[1.325, 0.344, 2.345]} scale={197.957} />
        <mesh geometry={nodes.Cube017_Material002_0.geometry} material={materials['Material.002']} position={[170.121, 2244.936, 1707.576]} rotation={[2.566, -0.263, -1.027]} scale={174.541} />
        <mesh geometry={nodes.Cube018_Material002_0.geometry} material={materials['Material.002']} position={[632.863, 2425, 1085.351]} rotation={[1.685, -1.013, -2.296]} scale={174.541} />
        <mesh geometry={nodes.Cube019_Material002_0.geometry} material={materials['Material.002']} position={[606.556, 2593.79, 823.889]} rotation={[1.522, -0.782, -2.363]} scale={92.075} />
        <mesh geometry={nodes.Cube020_Material002_0.geometry} material={materials['Material.002']} position={[-595.587, 2621.756, 1547.777]} rotation={[-0.749, -0.359, 0.367]} scale={117.847} />
        <mesh geometry={nodes.pied004_Material_0.geometry} material={materials.Material} position={[-1632.207, 777.618, 353.183]} rotation={[-Math.PI / 2, 0, 0.371]} scale={47.871} />
        <mesh geometry={nodes.pied005_Material_0.geometry} material={materials.Material} position={[-855.161, 825.048, -1229.883]} rotation={[-Math.PI / 2, 0, 2.979]} scale={68.293} />
        <mesh geometry={nodes.Cube021_Material002_0.geometry} material={materials['Material.002']} position={[1128.26, 2559.812, -351.176]} rotation={[-1.1, -0.182, -0.003]} scale={175.809} />
        <mesh geometry={nodes.Cube022_Material002_0.geometry} material={materials['Material.002']} position={[818.091, 2618.618, -1436.207]} rotation={[-1.955, -0.298, -0.528]} scale={230.852} />
        <mesh geometry={nodes.Cube023_Material002_0.geometry} material={materials['Material.002']} position={[1650.844, 2632.73, -1342.014]} rotation={[-1.848, 0.231, -0.379]} scale={230.852} />
        <mesh geometry={nodes.Cube024_Material002_0.geometry} material={materials['Material.002']} position={[504.569, 2523.824, -910.273]} rotation={[-1.557, -0.609, -0.424]} scale={149.641} />
        <mesh geometry={nodes.Cube025_Material002_0.geometry} material={materials['Material.002']} position={[1898.512, 2527.215, -736.891]} rotation={[-1.409, 0.406, -0.354]} scale={175.48} />
        <mesh geometry={nodes.Cube026_Material002_0.geometry} material={materials['Material.002']} position={[1628.437, 2222.654, -1975.6]} rotation={[-2.314, 0.294, -0.316]} scale={113.799} />
        <mesh geometry={nodes.Cube027_Material002_0.geometry} material={materials['Material.002']} position={[1967.035, 2290.677, -1610.106]} rotation={[-2.147, 0.508, -0.132]} scale={86.738} />
        <mesh geometry={nodes.Cube028_Material002_0.geometry} material={materials['Material.002']} position={[487.08, 2394.492, -1511.866]} rotation={[-2.03, -0.465, -0.589]} scale={138.547} />
        <mesh geometry={nodes.Cube029_Material002_0.geometry} material={materials['Material.002']} position={[501.776, 2201.691, -1833.924]} rotation={[-2.286, -0.442, -0.629]} scale={[108.669, 108.668, 108.668]} />
        <mesh geometry={nodes.Cube030_Material002_0.geometry} material={materials['Material.002']} position={[419.582, 2356.144, -506.012]} rotation={[-1.171, -0.704, -0.297]} scale={113.433} />
        <mesh geometry={nodes.Cube031_Material002_0.geometry} material={materials['Material.002']} position={[14.305, 2070.847, -831.814]} rotation={[-1.441, -0.899, -0.441]} scale={113.433} />
        <mesh geometry={nodes.Cube032_Material002_0.geometry} material={materials['Material.002']} position={[1233.355, 2235.811, 13.367]} rotation={[-0.907, -0.008, 0.002]} scale={103.143} />
        <mesh geometry={nodes.Cube033_Material002_0.geometry} material={materials['Material.002']} position={[1381.258, 2371.419, -167.401]} rotation={[-0.922, 0.011, -0.006]} scale={70.45} />
        <mesh geometry={nodes.Cube034_Material002_0.geometry} material={materials['Material.002']} position={[2033.155, 2239.74, -337.205]} rotation={[-1.101, 0.589, -0.505]} scale={71.658} />
        <mesh geometry={nodes.Cube035_Material002_0.geometry} material={materials['Material.002']} position={[-1475.3, 1591.503, 269.662]} rotation={[1.613, -0.113, -1.359]} scale={61.118} />
        <mesh geometry={nodes.Cube036_Material002_0.geometry} material={materials['Material.002']} position={[-1269.36, 1397.132, 69.556]} rotation={[0.338, -0.8, -2.053]} scale={61.118} />
        <mesh geometry={nodes.Cube037_Material002_0.geometry} material={materials['Material.002']} position={[-1217.443, 1413.81, 181.643]} rotation={[1.577, -1.147, -1.662]} scale={41.743} />
        <mesh geometry={nodes.Cube038_Material002_0.geometry} material={materials['Material.002']} position={[-1414.055, 1264.887, -10.364]} rotation={[-0.085, -0.189, -1.659]} scale={61.118} />
        <mesh geometry={nodes.Cube039_Material002_0.geometry} material={materials['Material.002']} position={[-1481.737, 1484.937, 503.243]} rotation={[2.82, -0.124, -0.917]} scale={41.743} />
        <mesh geometry={nodes.Cube040_Material002_0.geometry} material={materials['Material.002']} position={[-1517.119, 1591.501, 417.042]} rotation={[2.133, -0.239, -0.953]} scale={41.743} />
        <mesh geometry={nodes.Cube041_Material002_0.geometry} material={materials['Material.002']} position={[-1619.78, 1456.004, 38.99]} rotation={[0.483, 0.302, -2.584]} scale={61.118} />
        <mesh geometry={nodes.Cube042_Material002_0.geometry} material={materials['Material.002']} position={[-1581.529, 1129.425, -0.615]} rotation={[-0.127, -0.17, -1.677]} scale={48.18} />
        <mesh geometry={nodes.Cube043_Material002_0.geometry} material={materials['Material.002']} position={[-1596.799, 1618.518, 367.022]} rotation={[1.78, 0.153, -1.38]} scale={26.44} />
        <mesh geometry={nodes.Cube044_Material002_0.geometry} material={materials['Material.002']} position={[-1415.756, 2147.807, -1255.387]} rotation={[-1.574, -0.527, -0.192]} scale={183.792} />
        <mesh geometry={nodes.Cube045_Material002_0.geometry} material={materials['Material.002']} position={[-735.002, 2068.16, -1199.097]} rotation={[-1.665, 0.472, -0.626]} scale={115.762} />
        <mesh geometry={nodes.Cube046_Material002_0.geometry} material={materials['Material.002']} position={[-910.7, 1831.296, -1641.834]} rotation={[-2.507, 0.18, 0.159]} scale={148.047} />
        <mesh geometry={nodes.Cube047_Material002_0.geometry} material={materials['Material.002']} position={[-1116.086, 1902.867, -610.698]} rotation={[-0.822, -0.278, -0.27]} scale={115.762} />
        <mesh geometry={nodes.Cube048_Material002_0.geometry} material={materials['Material.002']} position={[-1724.264, 1703.141, -1413.556]} rotation={[-2.057, -1.088, -2.231]} scale={115.762} />
        <mesh geometry={nodes.Cube049_Material002_0.geometry} material={materials['Material.002']} position={[-1776.89, 1607.574, -1222.804]} rotation={[-1.721, -1.134, -1.993]} scale={86.691} />
        <mesh geometry={nodes.Cube050_Material002_0.geometry} material={materials['Material.002']} position={[-1475.814, 2010.112, -1008.517]} rotation={[-1.096, -0.605, -0.062]} scale={113.956} />
        <mesh geometry={nodes.Cube051_Material002_0.geometry} material={materials['Material.002']} position={[-1311.277, 1768.87, -645.943]} rotation={[-0.811, -0.472, -0.221]} scale={70.877} />
        <mesh geometry={nodes.Cube052_Material002_0.geometry} material={materials['Material.002']} position={[-560.214, 1946.808, -767.763]} rotation={[-1.332, 0.372, -0.183]} scale={115.762} />
        <mesh geometry={nodes.Cube053_Material002_0.geometry} material={materials['Material.002']} position={[-494.128, 1922.011, -961.668]} rotation={[-1.656, 0.418, -0.106]} scale={49.717} />
        <mesh geometry={nodes.Cube054_Material009_0.geometry} material={materials['Material.009']} position={[1432.586, 820.396, 710.853]} rotation={[-Math.PI / 2, 0.13, 0]} scale={265.226} />
        <mesh geometry={nodes.Cube055_Material009_0.geometry} material={materials['Material.009']} position={[984.068, 816.17, 1010.197]} rotation={[-1.553, -0.353, 2.136]} scale={153.433} />
        <mesh geometry={nodes.Circle_Material010_0.geometry} material={materials['Material.010']} position={[45.883, 810.546, 2.919]} rotation={[-Math.PI / 2, 0, 0]} scale={2195.716} />
        <mesh geometry={nodes.Cube056_Material009_0.geometry} material={materials['Material.009']} position={[1000.043, 801.919, 464.736]} rotation={[-1.361, 0.08, -2.801]} scale={176.609} />
        <mesh geometry={nodes.Cube057_Material009_0.geometry} material={materials['Material.009']} position={[-581.202, 820.396, -401.414]} rotation={[-2.006, 0.205, 0.088]} scale={265.226} />
        <mesh geometry={nodes.Cube058_Material009_0.geometry} material={materials['Material.009']} position={[-156.784, 820.396, -225.793]} rotation={[-1.327, 0.162, -2.55]} scale={157.348} />
        <mesh geometry={nodes.Cube059_Material009_0.geometry} material={materials['Material.009']} position={[-216.07, 820.396, -584.33]} rotation={[-1.753, 0.229, -0.874]} scale={100.476} />
        <mesh geometry={nodes.Cube060_Material011_0.geometry} material={materials['Material.011']} position={[195.418, 775.324, -1654.867]} rotation={[-Math.PI / 2, 0, 0]} scale={49.872} />
        <mesh geometry={nodes.Cube061_Material011_0.geometry} material={materials['Material.011']} position={[117.5, 775.324, -1515.969]} rotation={[-Math.PI / 2, 0, 1.832]} scale={40.037} />
        <mesh geometry={nodes.Cube062_Material011_0.geometry} material={materials['Material.011']} position={[205.581, 808.511, -1556.622]} rotation={[-Math.PI / 2, 0, -2.313]} scale={32.309} />
        <mesh geometry={nodes.Cube063_Material011_0.geometry} material={materials['Material.011']} position={[-1110.112, 778.854, -141.239]} rotation={[-Math.PI / 2, 0, 1.176]} scale={33.957} />
        <mesh geometry={nodes.Cube064_Material011_0.geometry} material={materials['Material.011']} position={[-1043.23, 778.854, -55.886]} rotation={[-Math.PI / 2, 0, 3.008]} scale={27.26} />
        <mesh geometry={nodes.Cube065_Material011_0.geometry} material={materials['Material.011']} position={[-1045.707, 801.45, -121.891]} rotation={[-Math.PI / 2, 0, -1.137]} scale={21.998} />
        <mesh geometry={nodes.Cube066_Material011_0.geometry} material={materials['Material.011']} position={[1274.023, 780.738, 1138.782]} rotation={[-Math.PI / 2, 0, -2.53]} scale={25.462} />
        <mesh geometry={nodes.Cube067_Material011_0.geometry} material={materials['Material.011']} position={[1265.852, 780.738, 1057.885]} rotation={[-Math.PI / 2, 0, -0.698]} scale={20.44} />
        <mesh geometry={nodes.Cube068_Material011_0.geometry} material={materials['Material.011']} position={[1240.964, 797.682, 1100.706]} rotation={[-Math.PI / 2, 0, 1.44]} scale={16.495} />
        <mesh geometry={nodes.Cube069_Material011_0.geometry} material={materials['Material.011']} position={[-521.808, 764.498, 1285.246]} rotation={[-Math.PI / 2, -0.007, 0.204]} scale={25.462} />
        <mesh geometry={nodes.Cube070_Material011_0.geometry} material={materials['Material.011']} position={[-546.423, 764.337, 1362.739]} rotation={[-Math.PI / 2, -0.007, 2.035]} scale={20.44} />
        <mesh geometry={nodes.Cube071_Material011_0.geometry} material={materials['Material.011']} position={[-506.692, 781.54, 1333.317]} rotation={[-Math.PI / 2, -0.007, -2.11]} scale={16.495} />
        <mesh geometry={nodes.Cube072_Material011_0.geometry} material={materials['Material.011']} position={[435.436, 777.951, 26.581]} rotation={[-Math.PI / 2, 0, -2.012]} scale={38.03} />
        <mesh geometry={nodes.Cube073_Material011_0.geometry} material={materials['Material.011']} position={[365.058, 777.951, -72.391]} rotation={[-Math.PI / 2, 0, -0.18]} scale={30.53} />
        <mesh geometry={nodes.Cube074_Material011_0.geometry} material={materials['Material.011']} position={[364.39, 803.257, 1.581]} rotation={[-Math.PI / 2, 0, 1.958]} scale={24.637} />
        <mesh geometry={nodes.Cube075_Material013_0.geometry} material={materials['Material.013']} position={[2136.456, 2468.849, 1704.727]} rotation={[-Math.PI / 2, 0, 0]} scale={99.616} />
        <mesh geometry={nodes.Cube076_Material013_0.geometry} material={materials['Material.013']} position={[-940.623, 3674.675, 1627.457]} rotation={[-Math.PI / 2, 0, 0]} scale={254.334} />
        <mesh geometry={nodes.Cube077_Material013_0.geometry} material={materials['Material.013']} position={[1086.39, 3318.337, -129.208]} rotation={[-Math.PI / 2, 0, 0]} scale={92.319} />
        <mesh geometry={nodes.Cube078_Material013_0.geometry} material={materials['Material.013']} position={[-1484.747, 1641.362, 1189.742]} rotation={[-Math.PI / 2, 0, 0]} scale={71.178} />
        <mesh geometry={nodes.Cube079_Material013_0.geometry} material={materials['Material.013']} position={[1630.45, 1641.362, 212.426]} rotation={[-Math.PI / 2, 0, 0]} scale={65.119} />
        <mesh geometry={nodes.Cube080_Material013_0.geometry} material={materials['Material.013']} position={[411.546, 1137.924, -2540.867]} rotation={[-Math.PI / 2, 0, 0]} scale={71.339} />
        <mesh geometry={nodes.Cube081_Material013_0.geometry} material={materials['Material.013']} position={[-199.646, 4197.756, -1647.671]} rotation={[-Math.PI / 2, 0, 0]} scale={96.673} />
        <mesh geometry={nodes.Cube082_Material013_0.geometry} material={materials['Material.013']} position={[1630.693, 3066.523, -2120.784]} rotation={[-Math.PI / 2, 0, 0]} scale={62.821} />
        <mesh geometry={nodes.Cube083_Material013_0.geometry} material={materials['Material.013']} position={[988.256, 1760.584, 2484.809]} rotation={[-Math.PI / 2, 0, 0]} scale={77.929} />
        <mesh geometry={nodes.Cube084_Material013_0.geometry} material={materials['Material.013']} position={[-1249.576, 3550.534, -824.012]} rotation={[-Math.PI / 2, 0, 0]} scale={130.346} />
        <mesh geometry={nodes.Cube085_Material013_0.geometry} material={materials['Material.013']} position={[2092.527, 1222.816, -948.486]} rotation={[-Math.PI / 2, 0, 0]} scale={130.346} />
        <mesh geometry={nodes.Cube086_Material013_0.geometry} material={materials['Material.013']} position={[-2092.374, 2794.059, -214.306]} rotation={[-Math.PI / 2, 0, 0]} scale={96.673} />
        <mesh geometry={nodes.Cube_Material008_0.geometry} material={materials['Material.008']} position={[837.24, 3450.715, 997.787]} rotation={[-Math.PI / 2, 0, 0]} scale={52.654} />
        <mesh geometry={nodes.Cube001_Material008_0.geometry} material={materials['Material.008']} position={[900.071, 3532.542, 1005.924]} rotation={[-Math.PI / 2, 0, 0]} scale={110.577} />
        <mesh geometry={nodes.Cube002_Material008_0.geometry} material={materials['Material.008']} position={[824.771, 3590.5, 946.757]} rotation={[-Math.PI / 2, 0, 0]} scale={84.206} />
        <mesh geometry={nodes.Cube003_Material008_0.geometry} material={materials['Material.008']} position={[1303.122, 3611.438, 776.221]} rotation={[-Math.PI / 2, 0, 0]} scale={117.914} />
        <mesh geometry={nodes.Cube004_Material008_0.geometry} material={materials['Material.008']} position={[1298.528, 3602.602, 853.721]} rotation={[-Math.PI / 2, 0, 0]} scale={72.911} />
        <mesh geometry={nodes.Cube005_Material008_0.geometry} material={materials['Material.008']} position={[1670.808, 3884.431, 570.697]} rotation={[-Math.PI / 2, 0, 0]} scale={114.817} />
        <mesh geometry={nodes.Cube006_Material008_0.geometry} material={materials['Material.008']} position={[1562.087, 3916.704, 585.573]} rotation={[-Math.PI / 2, 0, 0]} scale={59.725} />
        <mesh geometry={nodes.Cube007_Material008_0.geometry} material={materials['Material.008']} position={[1603.859, 3959.943, 491.454]} rotation={[-Math.PI / 2, 0, 0]} scale={123.421} />
        <mesh geometry={nodes.Cube010_Material008_0.geometry} material={materials['Material.008']} position={[1670.064, 4033.491, 549.461]} rotation={[-Math.PI / 2, 0, 0]} scale={39.418} />
      </group>
    </group>
  )
}

useGLTF.preload('/house.glb')
